[mongodb]
mongodb-dev.pmpkdev.online

[catalogue]
catalogue-dev.pmpkdev.online

[redis]
redis-dev.pmpkdev.online

[cart]
cart-dev.pmpkdev.online

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.pmpkdev.online
CATALOGUE_HOST=catalogue-dev.pmpkdev.online
REDIS_HOST=redis-dev.pmpkdev.online