[mongodb]
mongodb-dev.pmpkdev.online

[catalogue]
catalogue-dev.pmpkdev.online

[redis]
redis-dev.pmpkdev.online

[user]
user-dev.pmpkdev.online

[cart]
cart-dev.pmpkdev.online

[mysql]
mysql-dev.pmpkdev.online

[shipping]
shipping-dev.pmpkdev.online

[rabbitmq]
rabbitmq-dev.pmpkdev.online

[payment]
payment-dev.pmpkdev.online

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.pmpkdev.online
CATALOGUE_HOST=catalogue-dev.pmpkdev.online
REDIS_HOST=redis-dev.pmpkdev.online
MYSQL_HOST=mysql-dev.pmpkdev.online
SHIPPING_HOST=shipping-dev.pmpkdev.online
RABBITMQ_HOST=rabbitmq-dev.pmpkdev.online